name: Fight Childhood Obesity
favicon: null
layout_spectrum: 0.9517532445024699
typography_spectrum: 0.5127827685791999
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.14094053697772324
  lightness: 0.3600848913192749
  saturation: 0.7245688473340124
  rhythmicContrast: 0.051038369070738554
purpose: []
